service: aws-node-simple-http-endpoint

frameworkVersion: "3" # Serverless version

provider:
  name: aws
  runtime: nodejs12.x
  iam:
    deploymentRole: arn:aws:iam::765557214082:role/ServerlessCloudFormationExecutionRole

functions:
  localGreeting:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
plugins:
  - serverless-offline