service: aws-node-simple-http-endpoint

frameworkVersion: "3.18.2" # Serverless version

provider:
  name: aws
  runtime: nodejs12.x

functions:
  localGreeting:
    handler: handler.endpoint
    events:
      - http:
          path: ping
          method: get
